FROM python:3.10-slim

WORKDIR /app
COPY requirements-actions.txt ./
RUN pip install --no-cache-dir -r requirements-actions.txt
COPY actions ./actions

EXPOSE 5055
CMD ["rasa", "run", "actions", "--host", "0.0.0.0", "--port", "5055", "--actions", "actions"]
